name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          cd asr_system_backend
          pip install -r requirements.txt
      - name: Lint
        run: |
          cd asr_system_backend
          flake8 app || true
      - name: Alembic migrate
        run: |
          cd asr_system_backend
          alembic upgrade head
      - name: Run tests
        run: |
          cd asr_system_backend
          pytest

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: |
          cd asr_system_frontend
          npm install
      - name: Lint
        run: |
          cd asr_system_frontend
          npm run lint || true
      - name: Build
        run: |
          cd asr_system_frontend
          npm run build 